#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_homepage:
    path: /
    controller: App\Controller\HomeController::index
produit:
    path: /products/liste
    controller: App\Controller\ProductController::liste